In [ ]:
!pip install catboost

In [ ]:
!git clone https://ueberchild:mypass@github.com/trmasha2002/nti_final_bdimo.git

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
data_prefix = ''
if os.path.isdir('data/'):
    data_prefix = 'data/'
if os.path.isdir('nti_final_bdimo'):
    data_prefix = 'nti_final_bdimo/'
    if os.path.isdir('nti_final_bdimo/data'):
        data_prefix += 'data/'
del os
studs_info = pd.read_csv(data_prefix + 'studs_info.csv')
X_train = pd.read_csv(data_prefix + 'X_train.csv', index_col=0)
y_train = pd.read_csv(data_prefix + 'y_train.csv',index_col=0)
X_test = pd.read_csv(data_prefix + 'X_test.csv', index_col=0)

In [3]:
X_train

,STD_ID,НАПРАВЛЕНИЕ,ГОД,КУРС,СЕМЕСТР,АТТЕСТАЦИЯ,ДИСЦИПЛИНА
51081,175711,38.03.02 Менеджмент,2018-2019,2.0,4.0,Экзамен,Маркетинг
72921,100647,31.05.01 Лечебное дело,2015-2016,3.0,5.0,Экзамен,"Пропедевтика внутренних болезней, лучевая диаг..."
96438,199311,31.05.03 Стоматология,2019-2020,1.0,1.0,Экзамен,Химия
273044,162002,38.03.02 Менеджмент,2017-2018,2.0,3.0,Экзамен,Статистика
371309,108384,31.05.01 Лечебное дело,2018-2019,5.0,9.0,Экзамен,Педиатрия
...,...,...,...,...,...,...,...
224856,176141,40.03.01 Юриспруденция,2017-2018,1.0,2.0,Курсовая работа,Конституционное право
260998,182794,31.05.01 Лечебное дело,2018-2019,2.0,4.0,Экзамен,Нормальная физиология
57245,162391,31.05.01 Лечебное дело,2016-2017,1.0,2.0,Дифференцированный зачет,Иностранный язык
218529,202479,38.03.01 Экономика,2017-2018,1.0,1.0,Дифференцированный зачет,Информатика
233318,182325,08.03.01 Строительство,2018-2019,2.0,3.0,Курсовая работа,Технологические процессы в строительстве

In [4]:
def date_cleaning(X):
    for i in range(len(X)):
        X.at[i, 'Дата выдачи'] = str(X.at[i, 'Дата выдачи'])[:str(X.at[i, 'Дата выдачи']).find(' 00:00:00')]
        X.at[i, 'Дата выдачи'] = X.at[i, 'Дата выдачи'].replace('3017', '2017').replace('2105', '2015')
        if str(X.at[i, 'Дата выдачи']).startswith('29'):
            X.at[i, 'Дата выдачи'] = '20' + str(X.at[i, 'Дата выдачи'])[2:]
        for t_r in (('27.06.021', '2014-06-27'), ('24.06.021', '2016-06-24'), 
        ('20.06.021', '2017-06-29'), ('25.06.021', '2015-06-25'), ('6014-06-26', '2014-06-26'),
        ('2017-01-', '2017-01-01'), ('2017-01-0', '2017-01-05'), ('2017-06-', '2017-06-15'),
        ('2014-03-0', '2014-03-03'), ('6014-01-01', '2014-01-01'), ('20.02.100', '2009-02-20')):
            if X.at[i, 'Дата выдачи'] == t_r[0]:
                X.at[i, 'Дата выдачи'] = t_r[1]
        if X.at[i, 'Дата выдачи'] in ('na', 'Non', 'N', 'Na', '6014-', '6', '6014', '601', '60', '291', '29'):
            X.at[i, 'Дата выдачи'] = None
        X.at[i, 'Дата выдачи'] = pd.to_datetime(X.at[i, 'Дата выдачи'])
    X['Дата выдачи'] = pd.to_datetime(X['Дата выдачи'])
    return X
studs_info = date_cleaning(studs_info).sort_values(by='Дата выдачи').drop_duplicates(
    keep='last', subset='STD_ID'
)

In [5]:
studs_info

,STD_ID,number,Пол,Статус,Дата выпуска,Категория обучения,Форма обучения,Шифр,направление (специальность),,Образование,Дата выдачи,Что именно закончил
2660,193905,5208.0,Ж,СТ,NaN,ДОГ,З,44.03.03,Специальное (дефектологическое) образование,6324.0,СП,1983-06-30,ТЕХНИКУМ ДРУГОЙ
5449,113179,1216.0,Ж,СТ,NaN,БП,Д,31.05.01,Лечебное дело,2976.0,СП,1986-03-17,ИНОГОРОДНЯЯ СРЕДНЯЯ ШКОЛА
2066,198298,6933.0,М,СТ,NaN,ДОГ,З,38.03.02,Менеджмент,7099.0,СП,1986-08-28,ТЕХНИКУМ ДРУГОЙ
1730,192576,5045.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,10920.0,СР,1989-06-17,"СОШ , МАРЕВО"
3378,182240,4975.0,Ж,СТ,NaN,ДОГ,З,37.03.01,Психология,10866.0,СП,1989-06-28,БОРОВИЧСКИЙ ПЕДАГОГИЧЕСКИЙ КОЛЛЕДЖ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5441,192577,6545.0,М,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaT,NaN
5442,191636,5389.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaT,NaN
5443,191638,5422.0,М,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaT,NaN
5464,191625,3765.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaT,NaN
5465,194978,5245.0,Ж,СТ,NaN,ДОГ,Д,31.05.01,Лечебное дело,NaN,NaN,NaT,NaN

In [6]:
X_train['mark'] = y_train['mark']

In [7]:
studs_info = studs_info.set_index('STD_ID')
def merge_with_studs_info(X):
    for c in set(studs_info.columns) - {'STD_ID', '   ', '   number', 'Дата выпуска', 
                                      'Статус', 'направление (специальность)'}:
        X[c] = X.apply(lambda row: studs_info.at[row['STD_ID'], c], axis = 1)
    return X
X_train = merge_with_studs_info(X_train).drop(columns='НАПРАВЛЕНИЕ')
X_test = merge_with_studs_info(X_test).drop(columns='НАПРАВЛЕНИЕ')
del studs_info

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

to_encode = ('АТТЕСТАЦИЯ', 'ДИСЦИПЛИНА', 'Что именно закончил')
for t_e in to_encode:
    X_train[t_e] = X_train[t_e].fillna('NaN').astype(str)
    X_test[t_e] = X_test[t_e].fillna('NaN').astype(str)
    le.fit(X_train.append(X_test, sort=True).loc[:,t_e])
    X_train.loc[:, t_e] = le.transform(X_train.loc[:,t_e])
    X_test.loc[:, t_e] = le.transform(X_test.loc[:, t_e])

In [9]:
def cipher_splitting(X):
    X = X.merge(pd.DataFrame(X.Шифр.str.split('.').tolist(), 
        columns = ['XX_cipher','YY_cipher', 'ZZ_cipher']), 
        on = X.index).drop(columns='key_0')
    X['XX_ZZ_cipher'] = X[['XX_cipher', 'YY_cipher']].agg('.'.join, axis=1)
    return X.drop(columns=['Шифр', 'ZZ_cipher'])
X_train = cipher_splitting(X_train)
X_test = cipher_splitting(X_test)

In [10]:
stud_mean_mark = X_train.groupby("STD_ID").mean()["mark"]
X_train.loc[:,"stud_mean"] = X_train.loc[:,"STD_ID"].map(stud_mean_mark)
X_test.loc[:,"stud_mean"] = X_test.loc[:,"STD_ID"].map(stud_mean_mark)

In [11]:
def cyrillic_cleaning(X):
    trans = lambda x: x.translate({ord(a):ord(b) for a, b in zip(
            u"абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
            u"abvgdeejzijklmnoprstufhzcss_y_euaABVGDEEJZIJKLMNOPRSTUFHZCSS_Y_EUA")})

    for c in tuple(X.columns):
        new_c = trans(c)
        X.rename(columns={c:trans(new_c)}, inplace = True)
        if X[new_c].dtype.name in ('str', 'object', 'category'):
            for ro in range(len(X)):
                if type(X.at[ro, new_c]) == str:
                    X.at[ro, new_c] = trans(X.at[ro, new_c])
    return X
X_train = cyrillic_cleaning(X_train)
X_test = cyrillic_cleaning(X_test)

In [12]:
for i in range(len(X_train)):
    X_train.at[i, 'GOD'] = str(X_train.at[i, 'GOD'])[:str(X_train.at[i, 'GOD']).find('-')]
for i in range(len(X_test)):
    X_test.at[i, 'GOD'] = str(X_test.at[i, 'GOD'])[:str(X_test.at[i, 'GOD']).find('-')]
X_train['GOD'] = X_train['GOD'].astype(int)
X_test['GOD'] = X_test['GOD'].astype(int)

X_train['KURS'] = X_train['KURS'].astype(int)
X_test['KURS'] = X_test['KURS'].astype(int)

In [13]:
def add_years_from_prev_edu(X):
    def to_apply(row):
        if type(row['Data vydaci']) == pd._libs.tslibs.nattype.NaTType:
            return None
        return row['GOD'] - row['Data vydaci'].year + 1 - row['KURS']
    X['years_from_prev_edu'] = X.apply(to_apply, axis=1)
    return X
X_train = add_years_from_prev_edu(X_train).drop(columns='Data vydaci')
X_test = add_years_from_prev_edu(X_test).drop(columns='Data vydaci')

In [14]:
def clear_nans(X):
    X['Obrazovanie'] = X['Obrazovanie'].fillna('nan')
    X['stud_mean'] = X['stud_mean'].fillna(X_train.append(X_test, 
                                  sort=True)['stud_mean'].mean()) # 4.18
    X['years_from_prev_edu'] = X['years_from_prev_edu'].fillna(X_train.append(X_test, 
                                  sort=True)['years_from_prev_edu'].mean()) # ?
    return X
X_train = clear_nans(X_train)
X_test = clear_nans(X_test)

In [15]:
X_train['male'] = X_train['Pol'].map({'M': True, 'J': False})
X_train.drop(columns='Pol', inplace=True)
X_test['male'] = X_test['Pol'].map({'M': True, 'J': False})
X_test.drop(columns='Pol', inplace=True)

X_train['paid_edu'] = X_train['Kategoria obucenia'].map({'DOG': True, 'BP': False})
X_train.drop(columns='Kategoria obucenia', inplace=True)
X_test['paid_edu'] = X_test['Kategoria obucenia'].map({'DOG': True, 'BP': False})
X_test.drop(columns='Kategoria obucenia', inplace=True)

X_train['first_semester'] = X_train['SEMESTR'].mod(2)
X_train.drop(columns='SEMESTR', inplace=True)
X_test['first_semester'] = X_test['SEMESTR'].mod(2)
X_test.drop(columns='SEMESTR', inplace=True)

In [16]:
int_cols = ['years_from_prev_edu']
str_cols = ['KURS', 'Cto imenno zakoncil', 'XX_cipher', 'YY_cipher', 'ATTESTAZIA',
    'DISZIPLINA', 'GOD', 'XX_ZZ_cipher', 'Obrazovanie', 'Forma obucenia']
bool_cols = ['male', 'first_semester', 'paid_edu']
for c in int_cols:
    X_train[c] = X_train[c].astype(int)
    X_test[c] = X_test[c].astype(int)
for c in str_cols:
    X_train[c] = X_train[c].astype(str)
    X_test[c] = X_test[c].astype(str)
for c in bool_cols:
    X_train[c] = X_train[c].astype(bool)
    X_test[c] = X_test[c].astype(bool)

In [17]:
for c in X_train.columns:
    print(repr(c), 'of type', X_train[c].dtype, 'contains', len(X_train[c].unique()), 
        'unique values and', X_train[c].isna().sum(), 'nans')

'STD_ID' of type int64 contains 5084 unique values and 0 nans
'GOD' of type object contains 7 unique values and 0 nans
'KURS' of type object contains 6 unique values and 0 nans
'ATTESTAZIA' of type object contains 5 unique values and 0 nans
'DISZIPLINA' of type object contains 1400 unique values and 0 nans
'mark' of type int64 contains 3 unique values and 0 nans
'Forma obucenia' of type object contains 3 unique values and 0 nans
'Cto imenno zakoncil' of type object contains 225 unique values and 0 nans
'Obrazovanie' of type object contains 8 unique values and 0 nans
'XX_cipher' of type object contains 28 unique values and 0 nans
'YY_cipher' of type object contains 3 unique values and 0 nans
'XX_ZZ_cipher' of type object contains 37 unique values and 0 nans
'stud_mean' of type float64 contains 916 unique values and 0 nans
'years_from_prev_edu' of type int64 contains 32 unique values and 0 nans
'male' of type bool contains 2 unique values and 0 nans
'paid_edu' of type bool contains 2 unique values and 0 nans
'first_semester' of type bool contains 2 unique values and 0 nans

In [18]:
# import xgboost as xgb
# from sklearn.model_selection import cross_val_score
# model = xgb.XGBClassifier(max_depth=10, n_estimators=1300, learning_rate=0.07)
# print(cross_val_score(model, X_train.drop(columns=['STD_ID', 'mark']), 
#                 X_train['mark'], scoring = 'neg_mean_absolute_error')) #

In [19]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(random_seed = 1489, border_count = 254,
    iterations = 1300, one_hot_max_size = 2, depth = 10, learning_rate = 0.07,
    cat_features = str_cols + bool_cols, logging_level = 'Silent')

model.fit(X_train.drop(columns=['STD_ID', 'mark']), X_train['mark'])

In [20]:
import datetime

y_pred = pd.read_csv(data_prefix + 'sample_submission.csv',index_col=0)
y_pred["mark"] = model.predict(X_test.drop(columns=['STD_ID']))
y_pred.to_csv("submission" + str(datetime.datetime.now()) + ".csv")